export const CALCULATE_RESULT_LOADING = 'CALCULATE_RESULT_LOADING';
export const CALCULATE_RESULT_SUCCESS = 'CALCULATE_RESULT_SUCCESS';
export const CALCULATE_RESULT_ERROR = 'CALCULATE_RESULT_ERROR';
export const SNACKBAR_SUCCESS = 'SNACKBAR_SUCCESS';
export const SNACKBAR_ERROR = 'SNACKBAR_ERROR';
export const SNACKBAR_CLOSE = 'SNACKBAR_CLOSE';
